- hosts: terraform-ansible
  # become: yes
  tasks:
    - name: Installing python3, virtualenv
      apt:
        pkg:
        - python3
        - virtualenv
        update_cache: yes
      become: yes
    - name: Git Clone # Download the project
      ansible.builtin.git:
        repo: "https://github.com/guilhermeonrails/clientes-leo-api.git"
        dest: /home/ubuntu/web
        version: master
        force: yes # Force the clone to overwrite files if they already exist.
    - name: Installing dependencies with pip (Django and Django Rest)
      pip:
        virtualenv: /home/ubuntu/web/venv
        requirements: /home/ubuntu/web/requirements.txt
    # - name: Verifying if the project already exists
    #   stat: # checking if the file exists in the directory
    #     path: /home/ubuntu/web/setup/settings.py
    #   register: project_exists # registering the result of the stat command, in this case True or False
    # - name: Starting the Project
    #   shell: '. /home/ubuntu/web/venv/bin/activate; django-admin startproject setup /home/ubuntu/web/'
    #   when: not project_exists.stat.exists # if the project doesn't exist, start the project
    #   # ignore_errors: yes # if the project already exists, ignore the error. By default, Ansible will fail the playbook if the project already exists. Use this parameter with caution, evaluate possible issues that may occur.
    - name: Changing the hosts in the settings.py file
      lineinfile:
        path: /home/ubuntu/web/setup/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes
    - name: Configuring the database # In Django specifically, doesn't return error if we run twice, but it just try to run and finish the execution without errors.
      shell: '. /home/ubuntu/web/venv/bin/activate; python /home/ubuntu/web/manage.py migrate'
    - name: Loading initial data # Provided by the development team
      shell: '. /home/ubuntu/web/venv/bin/activate; python /home/ubuntu/web/manage.py loaddata clientes.json'
    - name: Starting the server
      shell: '. /home/ubuntu/web/venv/bin/activate; nohup python /home/ubuntu/web/manage.py runserver 0.0.0.0:8000 &'
      