- hosts: terraform-ansible
  become: yes

  tasks:
    - name: Create the file
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Done with Terraform and Ansible!<h1>"
    - name: Starting the server
      shell: "systemctl start httpd && systemctl enable httpd"
