- hosts: terraform-ansible
  # become: yes
  tasks:
    - name: Installing python3, virtualenv
      yum:
        pkg:
        - python3
        - virtualenv
        update_cache: yes
      become: yes
    - name: Installing dependencies with pip (Django and Django Rest)
      pip:
        virtualenv: /home/ec2-user/web/venv
        name:
        - django
        - djangorestframework
    - name: Starting the Project
      shell: '. /home/ec2-user/web/venv/bin/activate; django-admin startproject setup /home/ec2-user/web/'
      # ignore_errors: yes
    - name: Changing the hosts in the settings.py file
      lineinfile:
        path: /home/ec2-user/web/setup/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes